### ISSUE TITLE
Inviseo Token

### ISSUE THREAD

**Issue by vincent-inviseo** [Inviseo/InviseoBox#31]
Le `<INVISEOBOX_TOKEN>` correspond -til au worker ID au moment de l'enregistrement de la inviseobox sur le logiciel  ou a la propriété token renvoyé par l'api ?

```yaml
version: "3"
services:
  inviseoboxbox:
    image: ghcr.io/inviseo/inviseobox:latest
    container_name: inviseobox
    privileged: true
    user: root
    restart: always
    pull_policy: always
    environment:
      - token=<INVISEOBOX_TOKEN>
      - interval=1800
      - url=<API_URL>
```
